name: rtoexam

description: A simple Flutter quiz app with one question and four options.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - questions.json
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
